# build-FBPBlockChainLayer:
# 	python3 -m pip install -r requirements.txt -t $(ARTIFACTS_DIR)/python
# 	cp -r $(CURDIR)/fbpblockchain $(ARTIFACTS_DIR)/python/fbpblockchain

build-FBPBlockChainLayer:
	python3 -m pip install -r requirements.txt -t $(ARTIFACTS_DIR)/python
	cp -r fbpblockchain $(ARTIFACTS_DIR)/python/fbpblockchain

